version: 0.0
os: linux
files:
  - source: /scripts/start_container.sh
    destination: /home/ubuntu/start_container.sh

permissions:
  - object: /home/ubuntu/start_container.sh
    pattern: '**/*'
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: /home/ubuntu/start_container.sh
      timeout: 180
      runas: ubuntu


