version: 0.0
os: linux
files:
  - source: artifacts/
    destination: /home/ec2-user/deployment/

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/load_docker_image.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root

